// <auto-generated />
using Chirper_CS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chirper_CS.Migrations
{
    [DbContext(typeof(ChirperDbContext))]
    partial class ChirperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chirper_CS.Models.Chirp", b =>
                {
                    b.Property<int>("ChirpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChirpId"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChirpId");

                    b.HasIndex("UserId");

                    b.ToTable("Chirps");

                    b.HasData(
                        new
                        {
                            ChirpId = -50,
                            Message = "Chirp #-50",
                            UserId = -33
                        },
                        new
                        {
                            ChirpId = -49,
                            Message = "Chirp #-49",
                            UserId = -15
                        },
                        new
                        {
                            ChirpId = -48,
                            Message = "Chirp #-48",
                            UserId = -47
                        },
                        new
                        {
                            ChirpId = -47,
                            Message = "Chirp #-47",
                            UserId = -14
                        },
                        new
                        {
                            ChirpId = -46,
                            Message = "Chirp #-46",
                            UserId = -6
                        },
                        new
                        {
                            ChirpId = -45,
                            Message = "Chirp #-45",
                            UserId = -43
                        },
                        new
                        {
                            ChirpId = -44,
                            Message = "Chirp #-44",
                            UserId = -3
                        },
                        new
                        {
                            ChirpId = -43,
                            Message = "Chirp #-43",
                            UserId = -14
                        },
                        new
                        {
                            ChirpId = -42,
                            Message = "Chirp #-42",
                            UserId = -30
                        },
                        new
                        {
                            ChirpId = -41,
                            Message = "Chirp #-41",
                            UserId = -22
                        },
                        new
                        {
                            ChirpId = -40,
                            Message = "Chirp #-40",
                            UserId = -1
                        },
                        new
                        {
                            ChirpId = -39,
                            Message = "Chirp #-39",
                            UserId = -17
                        },
                        new
                        {
                            ChirpId = -38,
                            Message = "Chirp #-38",
                            UserId = -24
                        },
                        new
                        {
                            ChirpId = -37,
                            Message = "Chirp #-37",
                            UserId = -14
                        },
                        new
                        {
                            ChirpId = -36,
                            Message = "Chirp #-36",
                            UserId = -16
                        },
                        new
                        {
                            ChirpId = -35,
                            Message = "Chirp #-35",
                            UserId = -31
                        },
                        new
                        {
                            ChirpId = -34,
                            Message = "Chirp #-34",
                            UserId = -29
                        },
                        new
                        {
                            ChirpId = -33,
                            Message = "Chirp #-33",
                            UserId = -33
                        },
                        new
                        {
                            ChirpId = -32,
                            Message = "Chirp #-32",
                            UserId = -16
                        },
                        new
                        {
                            ChirpId = -31,
                            Message = "Chirp #-31",
                            UserId = -37
                        },
                        new
                        {
                            ChirpId = -30,
                            Message = "Chirp #-30",
                            UserId = -30
                        },
                        new
                        {
                            ChirpId = -29,
                            Message = "Chirp #-29",
                            UserId = -38
                        },
                        new
                        {
                            ChirpId = -28,
                            Message = "Chirp #-28",
                            UserId = -39
                        },
                        new
                        {
                            ChirpId = -27,
                            Message = "Chirp #-27",
                            UserId = -46
                        },
                        new
                        {
                            ChirpId = -26,
                            Message = "Chirp #-26",
                            UserId = -14
                        },
                        new
                        {
                            ChirpId = -25,
                            Message = "Chirp #-25",
                            UserId = -24
                        },
                        new
                        {
                            ChirpId = -24,
                            Message = "Chirp #-24",
                            UserId = -3
                        },
                        new
                        {
                            ChirpId = -23,
                            Message = "Chirp #-23",
                            UserId = -38
                        },
                        new
                        {
                            ChirpId = -22,
                            Message = "Chirp #-22",
                            UserId = -13
                        },
                        new
                        {
                            ChirpId = -21,
                            Message = "Chirp #-21",
                            UserId = -4
                        },
                        new
                        {
                            ChirpId = -20,
                            Message = "Chirp #-20",
                            UserId = -16
                        },
                        new
                        {
                            ChirpId = -19,
                            Message = "Chirp #-19",
                            UserId = -20
                        },
                        new
                        {
                            ChirpId = -18,
                            Message = "Chirp #-18",
                            UserId = -45
                        },
                        new
                        {
                            ChirpId = -17,
                            Message = "Chirp #-17",
                            UserId = -45
                        },
                        new
                        {
                            ChirpId = -16,
                            Message = "Chirp #-16",
                            UserId = -5
                        },
                        new
                        {
                            ChirpId = -15,
                            Message = "Chirp #-15",
                            UserId = -13
                        },
                        new
                        {
                            ChirpId = -14,
                            Message = "Chirp #-14",
                            UserId = -30
                        },
                        new
                        {
                            ChirpId = -13,
                            Message = "Chirp #-13",
                            UserId = -10
                        },
                        new
                        {
                            ChirpId = -12,
                            Message = "Chirp #-12",
                            UserId = -48
                        },
                        new
                        {
                            ChirpId = -11,
                            Message = "Chirp #-11",
                            UserId = -22
                        },
                        new
                        {
                            ChirpId = -10,
                            Message = "Chirp #-10",
                            UserId = -3
                        },
                        new
                        {
                            ChirpId = -9,
                            Message = "Chirp #-9",
                            UserId = -6
                        },
                        new
                        {
                            ChirpId = -8,
                            Message = "Chirp #-8",
                            UserId = -27
                        },
                        new
                        {
                            ChirpId = -7,
                            Message = "Chirp #-7",
                            UserId = -13
                        },
                        new
                        {
                            ChirpId = -6,
                            Message = "Chirp #-6",
                            UserId = -34
                        },
                        new
                        {
                            ChirpId = -5,
                            Message = "Chirp #-5",
                            UserId = -2
                        },
                        new
                        {
                            ChirpId = -4,
                            Message = "Chirp #-4",
                            UserId = -11
                        },
                        new
                        {
                            ChirpId = -3,
                            Message = "Chirp #-3",
                            UserId = -8
                        },
                        new
                        {
                            ChirpId = -2,
                            Message = "Chirp #-2",
                            UserId = -4
                        },
                        new
                        {
                            ChirpId = -1,
                            Message = "Chirp #-1",
                            UserId = -43
                        });
                });

            modelBuilder.Entity("Chirper_CS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = -50,
                            Email = "user-50@gmail.com",
                            FullName = "User -50"
                        },
                        new
                        {
                            UserId = -49,
                            Email = "user-49@gmail.com",
                            FullName = "User -49"
                        },
                        new
                        {
                            UserId = -48,
                            Email = "user-48@gmail.com",
                            FullName = "User -48"
                        },
                        new
                        {
                            UserId = -47,
                            Email = "user-47@gmail.com",
                            FullName = "User -47"
                        },
                        new
                        {
                            UserId = -46,
                            Email = "user-46@gmail.com",
                            FullName = "User -46"
                        },
                        new
                        {
                            UserId = -45,
                            Email = "user-45@gmail.com",
                            FullName = "User -45"
                        },
                        new
                        {
                            UserId = -44,
                            Email = "user-44@gmail.com",
                            FullName = "User -44"
                        },
                        new
                        {
                            UserId = -43,
                            Email = "user-43@gmail.com",
                            FullName = "User -43"
                        },
                        new
                        {
                            UserId = -42,
                            Email = "user-42@gmail.com",
                            FullName = "User -42"
                        },
                        new
                        {
                            UserId = -41,
                            Email = "user-41@gmail.com",
                            FullName = "User -41"
                        },
                        new
                        {
                            UserId = -40,
                            Email = "user-40@gmail.com",
                            FullName = "User -40"
                        },
                        new
                        {
                            UserId = -39,
                            Email = "user-39@gmail.com",
                            FullName = "User -39"
                        },
                        new
                        {
                            UserId = -38,
                            Email = "user-38@gmail.com",
                            FullName = "User -38"
                        },
                        new
                        {
                            UserId = -37,
                            Email = "user-37@gmail.com",
                            FullName = "User -37"
                        },
                        new
                        {
                            UserId = -36,
                            Email = "user-36@gmail.com",
                            FullName = "User -36"
                        },
                        new
                        {
                            UserId = -35,
                            Email = "user-35@gmail.com",
                            FullName = "User -35"
                        },
                        new
                        {
                            UserId = -34,
                            Email = "user-34@gmail.com",
                            FullName = "User -34"
                        },
                        new
                        {
                            UserId = -33,
                            Email = "user-33@gmail.com",
                            FullName = "User -33"
                        },
                        new
                        {
                            UserId = -32,
                            Email = "user-32@gmail.com",
                            FullName = "User -32"
                        },
                        new
                        {
                            UserId = -31,
                            Email = "user-31@gmail.com",
                            FullName = "User -31"
                        },
                        new
                        {
                            UserId = -30,
                            Email = "user-30@gmail.com",
                            FullName = "User -30"
                        },
                        new
                        {
                            UserId = -29,
                            Email = "user-29@gmail.com",
                            FullName = "User -29"
                        },
                        new
                        {
                            UserId = -28,
                            Email = "user-28@gmail.com",
                            FullName = "User -28"
                        },
                        new
                        {
                            UserId = -27,
                            Email = "user-27@gmail.com",
                            FullName = "User -27"
                        },
                        new
                        {
                            UserId = -26,
                            Email = "user-26@gmail.com",
                            FullName = "User -26"
                        },
                        new
                        {
                            UserId = -25,
                            Email = "user-25@gmail.com",
                            FullName = "User -25"
                        },
                        new
                        {
                            UserId = -24,
                            Email = "user-24@gmail.com",
                            FullName = "User -24"
                        },
                        new
                        {
                            UserId = -23,
                            Email = "user-23@gmail.com",
                            FullName = "User -23"
                        },
                        new
                        {
                            UserId = -22,
                            Email = "user-22@gmail.com",
                            FullName = "User -22"
                        },
                        new
                        {
                            UserId = -21,
                            Email = "user-21@gmail.com",
                            FullName = "User -21"
                        },
                        new
                        {
                            UserId = -20,
                            Email = "user-20@gmail.com",
                            FullName = "User -20"
                        },
                        new
                        {
                            UserId = -19,
                            Email = "user-19@gmail.com",
                            FullName = "User -19"
                        },
                        new
                        {
                            UserId = -18,
                            Email = "user-18@gmail.com",
                            FullName = "User -18"
                        },
                        new
                        {
                            UserId = -17,
                            Email = "user-17@gmail.com",
                            FullName = "User -17"
                        },
                        new
                        {
                            UserId = -16,
                            Email = "user-16@gmail.com",
                            FullName = "User -16"
                        },
                        new
                        {
                            UserId = -15,
                            Email = "user-15@gmail.com",
                            FullName = "User -15"
                        },
                        new
                        {
                            UserId = -14,
                            Email = "user-14@gmail.com",
                            FullName = "User -14"
                        },
                        new
                        {
                            UserId = -13,
                            Email = "user-13@gmail.com",
                            FullName = "User -13"
                        },
                        new
                        {
                            UserId = -12,
                            Email = "user-12@gmail.com",
                            FullName = "User -12"
                        },
                        new
                        {
                            UserId = -11,
                            Email = "user-11@gmail.com",
                            FullName = "User -11"
                        },
                        new
                        {
                            UserId = -10,
                            Email = "user-10@gmail.com",
                            FullName = "User -10"
                        },
                        new
                        {
                            UserId = -9,
                            Email = "user-9@gmail.com",
                            FullName = "User -9"
                        },
                        new
                        {
                            UserId = -8,
                            Email = "user-8@gmail.com",
                            FullName = "User -8"
                        },
                        new
                        {
                            UserId = -7,
                            Email = "user-7@gmail.com",
                            FullName = "User -7"
                        },
                        new
                        {
                            UserId = -6,
                            Email = "user-6@gmail.com",
                            FullName = "User -6"
                        },
                        new
                        {
                            UserId = -5,
                            Email = "user-5@gmail.com",
                            FullName = "User -5"
                        },
                        new
                        {
                            UserId = -4,
                            Email = "user-4@gmail.com",
                            FullName = "User -4"
                        },
                        new
                        {
                            UserId = -3,
                            Email = "user-3@gmail.com",
                            FullName = "User -3"
                        },
                        new
                        {
                            UserId = -2,
                            Email = "user-2@gmail.com",
                            FullName = "User -2"
                        },
                        new
                        {
                            UserId = -1,
                            Email = "user-1@gmail.com",
                            FullName = "User -1"
                        });
                });

            modelBuilder.Entity("Chirper_CS.Models.Chirp", b =>
                {
                    b.HasOne("Chirper_CS.Models.User", "User")
                        .WithMany("Chirps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chirper_CS.Models.User", b =>
                {
                    b.Navigation("Chirps");
                });
#pragma warning restore 612, 618
        }
    }
}
